# Generated by Django 2.2.2 on 2020-12-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20201229_0739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
